### ISSUE TITLE
로그인 후 main.jsp 호출 시 에러가 발생합니다. 

### ISSUE THREAD

**Issue by sonsamho** [axboot/ax-boot-framework#42]
로그인 화면에서 id : system 으로 디폴트 설정 된 것으로 login 시 에러가 발생하는데 원인을 모르겠어서 질문 드립니다. 

2017-03-30 16:25:50 [http-bio-8080-exec-3] INFO  com.chequer.axboot.core.db.aop.StatementMethodInterceptor:invoke:149 
[query] - 2017-03-30 16:25:50 - 
    select
        distinct authgroupm0_.MENU_ID as col_0_0_ 
    from
        AUTH_GROUP_MAP_M authgroupm0_ 
    where
        authgroupm0_.GRP_AUTH_CD='S0001'

2017-03-30 16:25:50 [http-bio-8080-exec-3] INFO  com.chequer.axboot.core.db.aop.StatementMethodInterceptor:invoke:149 
[query] - 2017-03-30 16:25:50 - 
    select
        menu0_.MENU_ID as MENU_ID1_5_0_,
        program1_.PROG_CD as PROG_CD1_7_1_,
        menu0_.CREATED_AT as CREATED_2_5_0_,
        menu0_.CREATED_BY as CREATED_3_5_0_,
        menu0_.UPDATED_AT as UPDATED_4_5_0_,
        menu0_.UPDATED_BY as UPDATED_5_5_0_,
        menu0_.LEVEL as LEVEL6_5_0_,
        menu0_.MENU_GRP_CD as MENU_GRP7_5_0_,
        menu0_.MENU_NM as MENU_NM8_5_0_,
        menu0_.MULTI_LANGUAGE as MULTI_LA9_5_0_,
        menu0_.PARENT_ID as PARENT_10_5_0_,
        menu0_.PROG_CD as PROG_CD11_5_0_,
        menu0_.SORT as SORT12_5_0_,
        program1_.CREATED_AT as CREATED_2_7_1_,
        program1_.CREATED_BY as CREATED_3_7_1_,
        program1_.UPDATED_AT as UPDATED_4_7_1_,
        program1_.UPDATED_BY as UPDATED_5_7_1_,
        program1_.AUTH_CHECK as AUTH_CHE6_7_1_,
        program1_.DEL_AH as DEL_AH7_7_1_,
        program1_.EXL_AH as EXL_AH8_7_1_,
        program1_.FN1_AH as FN9_7_1_,
        program1_.FN2_AH as FN10_7_1_,
        program1_.FN3_AH as FN11_7_1_,
        program1_.FN4_AH as FN12_7_1_,
        program1_.FN5_AH as FN13_7_1_,
        program1_.PROG_NM as PROG_NM14_7_1_,
        program1_.PROG_PH as PROG_PH15_7_1_,
        program1_.REMARK as REMARK16_7_1_,
        program1_.SAV_AH as SAV_AH17_7_1_,
        program1_.SCH_AH as SCH_AH18_7_1_,
        program1_.TARGET as TARGET19_7_1_ 
    from
        MENU_M menu0_ 
    left outer join
        PROG_M program1_ 
            on menu0_.PROG_CD=program1_.PROG_CD 
    where
        menu0_.MENU_GRP_CD='SYSTEM_MANAGER' 
    order by
        menu0_.LEVEL asc,
        menu0_.SORT asc

2017-03-30 16:25:50 [http-bio-8080-exec-3] ERROR org.springframework.boot.web.support.ErrorPageFilter:forwardToErrorPage:176 Forwarding to error page from request [/jsp/main.jsp] due to exception [Unable to compile class for JSP: 

An error occurred at line: 26 in the jsp file: /WEB-INF/tags/script-lang.tag
'<>' operator is not allowed for source level below 1.7
23:     if (key.equals("*")) {
24:         json = JsonUtils.toJson(properties);
25:     } else {
26:         Map<String, String> filterMap = new HashMap<>();
27: 
28:         Enumeration enumeration = properties.keys();
29: 

Stacktrace:]
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 26 in the jsp file: /WEB-INF/tags/script-lang.tag
'<>' operator is not allowed for source level below 1.7
23:     if (key.equals("*")) {
24:         json = JsonUtils.toJson(properties);
25:     } else {
26:         Map<String, String> filterMap = new HashMap<>();
27: 
28:         Enumeration enumeration = properties.keys();
29: 

Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:490)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
	at org.apache.jasper.servlet.JspServletWrapper.loadTagFile(JspServletWrapper.java:247)
	at org.apache.jasper.compiler.TagFileProcessor.loadTagFile(TagFileProcessor.java:577)
	at org.apache.jasper.compiler.TagFileProcessor.access$000(TagFileProcessor.java:49)
	at org.apache.jasper.compiler.TagFileProcessor$TagFileLoaderVisitor.visit(TagFileProcessor.java:654)
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1553)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2392)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2444)
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2570)
	at org.apache.jasper.compiler.Node$NamedAttribute.accept(Node.java:1922)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2392)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2444)
	at org.apache.jasper.compiler.TagFileProcessor$TagFileLoaderVisitor.visit(TagFileProcessor.java:658)
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1553)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2392)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2444)
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2450)
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:474)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2392)
	at org.apache.jasper.compiler.TagFileProcessor.loadTagFiles(TagFileProcessor.java:672)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:230)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.chequer.axboot.core.filters.AXBootConfigFilter.doFilter(AXBootConfigFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.chequer.axboot.core.filters.AXBootCorsFilter.doFilter(AXBootCorsFilter.java:17)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.chequer.axboot.core.filters.AXBootLogbackMdcFilter.doFilter(AXBootLogbackMdcFilter.java:31)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.chequer.axboot.security.AXBootAuthenticationFilter.doFilter(AXBootAuthenticationFilter.java:33)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.chequer.axboot.core.filters.MultiReadableHttpServletRequestFilter.doFilter(MultiReadableHttpServletRequestFilter.java:15)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
2017-03-30 16:25:50 [http-bio-8080-exec-3] INFO  com.chequer.axboot.core.db.aop.StatementMethodInterceptor:invoke:149 
[query] - 2017-03-30 16:25:50 - 
    insert 
    into
        ERROR_LOG_M
        (ALERT_YN, ERROR_DATETIME, HEADER_MAP, HOST_NAME, LOGGER_NAME, MESSAGE, PARAMETER_MAP, PATH, PHASE, SERVER_NAME, SYSTEM, TRACE, USER_INFO, ID) 
    values
        ('N', '2017/03/30 16:25:50.568', '{"accept-language":"ko-KR","cookie":"JSESSIONID=D95A1A4AE70DEF4A7A6300235D57979D; 5383ba8c-12b3-45d8-84fc-012ce6294421=\"eyJ1c2VyQ2QiOiJzeXN0ZW0iLCJ1c2VyUHMiOiIkMmEkMTEkcnVWa29pZUNQZ2hOT0E2bXRLeldSZVo1RWU2NmhiZXF3dmxCVDF6Llc0Vk1ZY2tCbGQ2dUMiLCJ1c2VyTm0iOiLsi5zsiqTthZwg6rSA66as7J6QIiwibG9jYWxlIjoia29fS1IiLCJ0aW1lWm9uZSI6IkFzaWEvU2VvdWwiLCJtZW51R3JwQ2QiOiJTWVNURU1fTUFOQUdFUiIsImRhdGVGb3JtYXQiOiJ5eXl5LU1NLWRkIiwiZGF0ZVRpbWVGb3JtYXQiOm51bGwsInRpbWVGb3JtYXQiOiJISDptbTpzcyIsIm1lbnVIYXNoIjpudWxsLCJleHBpcmVzIjowLCJkZXRhaWxzIjp7fSwiYXV0aG9yaXR5TGlzdCI6WyJST0xFX0FTUF9BQ0NFU1MiLCJST0xFX1NZU1RFTV9NQU5BR0VSIl0sImF1dGhHcm91cExpc3QiOlsiUzAwMDEiXX0=.fhxhCRvXNcPshu21sWGGZ4bzLYJvIfenD8vZoPV7deg=\"","host":"localhost:8080","connection":"Keep-Alive","dnt":"1","accept-encoding":"gzip, deflate","accept":"text/html, application/xhtml+xml, */*","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"}', 'son-son', 'org.springframework.boot.web.support.ErrorPageFilter', 'Forwarding to error page from request [/jsp/main.jsp] due to exception [Unable to compile class for JSP: 

An error occurred at line: 26 in the jsp file: /WEB-INF/tags/script-lang.tag
'<>' operator is not allowed for source level below 1.7
23:     if (key.equals("*")) {
24:         json = JsonUtils.toJson(properties);
25:     } else {
26:         Map<String, String> filterMap = new HashMap<>();
27: 
28:         Enumeration enumeration = properties.keys();
29:

**Comment by aeei** [comment]
우선 Java를 JDK 1.8.0 이상의 버전을 사용하고 계신지 확인 부탁드립니다.
JDK 1.8.0 이상의 자바를 사용하고 계신다면 아래의 링크를 보고 문제를 해결하시면 될 것 같습니다.
- <http://www.technicalkeeda.com/java-tutorials/diamond-operator-is-not-allowed-for-source-level-below-1-7>
- <http://m.blog.naver.com/airwindtree/220239375824>

**Comment by go2basic** [comment]
Map<String, String> filterMap = new HashMap<String, String>();
--> 변경하시면 에러 안나네요.
